### ISSUE TITLE
bug: TypeError during Next.js build with @noble/hashes in viem

### ISSUE THREAD

**Issue by zeJabun** [wevm/viem#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.7.3

### Current Behavior

Issue occurs when updating wagmi/viem/@rainbow-me to v2.

When attempting to build a Next.js application, I encounter a `TypeError: ep is not a function` during the static generation phase. This error is thrown by the `sha3.js` file within the `@noble/hashes` package, which is required by the `viem` package. The build process fails while pre-rendering pages, indicating a possible issue with the server-side rendering of the application.

```
[...]
✓ Collecting page data    
Generating static pages (0/5)  [=   ]TypeError: ep is not a function
 at ../../node_modules/viem/node_modules/@noble/hashes/esm/sha3.js ([...]/turborepo-root/apps/alpha/.next/server/chunks/479.js:16:9868)
 at [...]/turborepo-root/apps/alpha/.next/server/chunks/479.js:1:38140
 at ../../node_modules/viem/_esm/utils/hash/keccak256.js ([...]/turborepo-root/apps/alpha/.next/server/chunks/479.js:16:10040)
 at [...]/turborepo-root/apps/alpha/.next/server/chunks/479.js:1:38140
[...]

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
```

### Expected Behavior

The expected behavior is for the Next.js application to build successfully without any type errors during the static generation phase, allowing all pages to be prerendered without any issues.

### Steps To Reproduce

1. Run the build command for a Next.js application (`pnpm run build` or equivalent).
2. Observe the build process until it reaches the static generation phase.
3. The TypeError is thrown, and the build fails while prerendering specific pages.

### Anything else?

The issue seems to stem from the interaction between `viem` and `@noble/hashes` during server-side rendering.

Using `next/dynamic` to disable server-side rendering for client-specific components resolves the issue. However, this approach introduces unnecessary complexity and configuration overhead. The application should build without the need for `next/dynamic`, as it did when using viem v1.x and wagmi v1.x.

`const ComponentC = dynamic(() => import('../components/C'), { ssr: false })`

Versions:
```
"viem": "2.7.13",
"wagmi": "2.5.7",
"@wagmi/core": "2.6.5"
"@rainbow-me/rainbowkit": "2.0.1",
"react": "18.2.0",
"next": "14.1",
"@tanstack/react-query": "5.22.2",
```

**Comment by zeJabun** [comment]
Upon further investigation, I have concluded that the issue does not stem directly from `viem`. It appears that the problem is likely due to the build configuration of an internal SDK package that depends on `viem` and is imported into this app. It seems I may need to adjust the build setup within our internal package. 

Closing this issue as the root cause is not a bug within `viem`. Thanks!
